### ISSUE TITLE
Multiple features 

### ISSUE THREAD

**Issue by leonwilly** [franciscomartinezdelrio/tsfgrnn#1]
First thank you for this algorithm and explanation. Is it possible to use this with multiple features similar to how other GRNN algorithms work. Where X is the table or matrix and Y is the training target?

**Comment by franciscomartinezdelrio** [comment]
Hello. For the moment it is not possible, you can only use autoregressive features. The following package: https://cran.r-project.org/package=grnn implement general GRNN, but it is not adapted to time series forecasting.
